### ISSUE TITLE
login and register page not created during install

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#282]
Rachid, author of Listimia reported that on the demo and on his localhost, installing UWP didn't automatically generate the register and login page.

We had to manually create them to fix the problem.

Please check if it is something that we can replicate.

Thanks

**Comment by wpdev10** [comment]
yes, I can regenerate the issue and I have applied the fixes. The thing is that the theme is registering menu item with same slug 'register' which is also the slug of our register page so the page is not created due to already register slug was found. So I have now checked the post type page and it is working fine.
