### ISSUE TITLE
Fresh install bugs

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#37]
Hi Giri,

I just installed the latest version to test it and I immediately see 2 things wrong.

1) http://www.dropct.com/users/ is empty. There should be the admin user.
2) http://www.dropct.com/profile/admin/ the profile page looks like that.

Please correct and let me know,

Thanks,

**Comment by mistergiri** [comment]
Hi paolo,

Users page looks ok to me.

https://www.dropbox.com/s/ojbe93406jel36a/Screenshot%202017-02-16%2014.58.17.png?dl=0

Profile page banner is broken.

https://www.dropbox.com/s/qjq83655hjpf96b/Screenshot%202017-02-16%2014.59.42.png?dl=0

I think thats because dropct website doesn't seem like it contain default banner image. 

I mean this one.

https://github.com/UsersWP/userswp/blob/master/public/assets/images/banner.png

I see 404 here.
http://www.dropct.com/wp-content/plugins/userswp/public/assets/images/banner.png

You seem like you missed some files.

Thanks.

**Comment by mistergiri** [comment]
https://github.com/mistergiri/userswp/commit/3e23292af1b38df03c8fba2f5ff5a79e33b9b962
