### ISSUE TITLE
No alert is prompted on registration form when set to auto approve

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#401]
If Registration Action is set to auto-approve, after clicking the "Create Account" button, you are redirected to the homepage without any notification if the registration was successful or not.

We should add a success alert like on image attached.

![Capture](https://user-images.githubusercontent.com/25163253/92291738-9994b980-eedf-11ea-84f5-3d89a5e82500.JPG)

I tested this here: https://wpgeo.directory/userswp/

Thanks

**Comment by wpdev10** [comment]
We have to redirect as after login it will be not possible to stay on the register page as the register page is not visible to the logged in users. So we redirect to the home page. If the registration is not successful then it will display error message above form.

**Comment by pol76** [comment]
I think we should redirect to the account page. That will make it clearer. 

@Stiofan what do you think?

**Comment by wpdev10** [comment]
We check for multiple things like if the user is coming from another page to register then we redirect back to there else if the Register Redirect Page is set then we redirect there but if auto approve + auto login is set and at last we redirect to the home page. I am changing it to the account page instead of the home page.
